const Head = () => {
  return (
    <>
      <title>Nextjs App</title>
      <meta name="viewport" content="width=device-width, inital-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    </>
  )
}

export default Head
